### ISSUE TITLE
向Minecraft服务器发送迷宫数据和路径信息?????

### ISSUE THREAD

**Issue by j1g5awi** [CSUAITeam19/DSExp_Maze#1]

**Comment by LovelyCatHyt** [comment]
想不到吧? 我们还联动了MC.
python 部分 调用一个叫做 mcpi 的插件向迷宫发送信息;
服务端使用Raspberry juice (spigot和bucket的插件) 作为实现套接字数据的监听和具体的操作
剩下的就好说了, 具体的墙和路径可以直接转化为对应的方块, 再推动盔甲架移动, 就能演示迷宫算法
顺便在空地上加点怪物生成, 放点收集品 (比如小花花), 还能整成多人小游戏

**Comment by LovelyCatHyt** [comment]
你可以直接下载release体验一下。虽然使用文档还没写全， 但是瞎按应该也能折腾出用法
先点开python图标的那个exe启动
